# Generated by Django 3.2.7 on 2023-09-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='top_seller',
            field=models.BooleanField(default=False, verbose_name='Top Agent'),
        ),
    ]
